### PR TITLE
demo-rv64-qemu-virt-supervisor: Don't use log-semihosting

### PR DESCRIPTION
**Pull request by ghost**
- Add log-stringbuf support to task/one-shot
- Disable use of semihosting for app/demo-rv64-qemu-virt-supervisor

### CODE REVIEW

**Comment by ghost** [comment]
To confirm: Humility is able to pull the logs from rv64 targets carrying this PR?

**Comment by ghost** [comment]
> To confirm: Humility is able to pull the logs from rv64 targets carrying this PR?

Yes, `humility logs` works just fine to pull logs from this target. You may need 'dev/drew/gdb_ports' though if you allow qemu to start its gdb server on 1234 (the default).

**Review by ghost — APPROVED** [review]
LGTM - Removes another obstacle to running beyond qemu.

**Review by beezow — APPROVED** [review]
Looks good.  We should probably think of doing this for the test cases in the future.

**Review by FawazTirmizi — APPROVED** [review]

**Comment by furquan-rivos** [comment]
Long term, we might want to support multiple logging mechanisms (semihosting, stringbuf, uart, flash) while allowing each app to select more than one mechanism at the same time. This might be required to make it easier for developers to debug the app under different scenarios.

**Comment by beezow** [comment]
> Long term, we might want to support multiple logging mechanisms (semihosting, stringbuf, uart, flash) while allowing each app to select more than one mechanism at the same time. This might be required to make it easier for developers to debug the app under different scenarios.

I was thinking a single logging task might make all of this easier.  Would there be a case where different tasks would want to log to different spots within an app?

**Comment by furquan-rivos** [comment]
> I was thinking a single logging task might make all of this easier. Would there be a case where different tasks would want to log to different spots within an app?

A single logging task makes a lot of sense. All the policies can be implemented as part of that single task instead of having to sprinkle the features across all the different tasks. I don't think we have to worry about different tasks wanting to log to different spots. It is an app-policy and not a per-task policy.

**Pull request merged**
