### PR TITLE
RV64 Qemu virt

### PR DESCRIPTION
**Pull request by furquan-rivos**

### CODE REVIEW

**Review by FawazTirmizi — CHANGES_REQUESTED** [review]
Can you add the `demo-rv64-qemu-virt` task to CI?

**Comment by furquan-rivos** [comment]
> Can you add the `demo-rv64-qemu-virt` task to CI?

Done

**Comment by furquan-rivos** [comment]
> > Can you add the `demo-rv64-qemu-virt` task to CI?
> 
> Done

Ok. I think this is done now. I added a new job `build64` that is used for triggering builds for 64-bit targets. I had to do this because we use `xtask64` instead of `xtask` for building 64-bit targets. Let's see if this workflow run looks good.

**Comment by furquan-rivos** [comment]
> > > Can you add the `demo-rv64-qemu-virt` task to CI?
> > 
> > 
> > Done
> 
> Ok. I think this is done now. I added a new job `build64` that is used for triggering builds for 64-bit targets. I had to do this because we use `xtask64` instead of `xtask` for building 64-bit targets. Let's see if this workflow run looks good.

Confirmed that the workflow run looks good. Artifacts generated by the run for rv64 test fine on qemu.

**Review by FawazTirmizi — APPROVED** [review]
LGTM, but I noticed that the builds for rv64 take a good deal longer. Any idea why this is the case?

**Comment by furquan-rivos** [comment]
> LGTM, but I noticed that the builds for rv64 take a good deal longer. Any idea why this is the case?

Probably just a one-off. I re-ran the workflow and the build time for rv64 looks reasonable: https://github.com/rivosinc/hubris/actions/runs/3095651044/jobs/5016831167

**Pull request merged**
