### PR TITLE
dev/furquan/main merge oct 21

### PR DESCRIPTION
**Pull request by furquan-rivos**

### CODE REVIEW

**Comment by furquan-rivos** [comment]
Waiting for https://github.com/rivosinc/hubris/pull/65 to be merged so that riscv-semihosting breakage is addressed.

**Comment by FawazTirmizi** [comment]
Any merge conflicts?

**Comment by furquan-rivos** [comment]
> Any merge conflicts?

I had one conflict for https://github.com/rivosinc/hubris/pull/63/commits/0053a60324b665bc4a6d3fbe6e0fe691715fca81 but nothing apart from that.

**Review by FawazTirmizi — DISMISSED** [review]

**Review by beezow — DISMISSED** [review]

**Comment by furquan-rivos** [comment]
@beezow looks like nix flake check is failing: https://github.com/rivosinc/hubris/actions/runs/3300635406/jobs/5445349052. Do you know how to start debugging?

**Comment by furquan-rivos** [comment]
> @beezow looks like nix flake check is failing: https://github.com/rivosinc/hubris/actions/runs/3300635406/jobs/5445349052. Do you know how to start debugging?

error: hash mismatch in fixed-output derivation '/nix/store/b1bp8zff3d1yamw0rc4vsdzvc0mc8izz-riscv-semihosting-ec93c72.drv':
         specified: sha256-JzQyv2/4F1FBclFZUsIOJ1TREaBIKQp/TOZhBSHyQGY=
            got:    sha256-sGa++ywE9kYw9VnPKeYyzaRJsYOzF0mNE7C9c2TdUNQ=

**Comment by furquan-rivos** [comment]
> > @beezow looks like nix flake check is failing: https://github.com/rivosinc/hubris/actions/runs/3300635406/jobs/5445349052. Do you know how to start debugging?
> 
> error: hash mismatch in fixed-output derivation '/nix/store/b1bp8zff3d1yamw0rc4vsdzvc0mc8izz-riscv-semihosting-ec93c72.drv': specified: sha256-JzQyv2/4F1FBclFZUsIOJ1TREaBIKQp/TOZhBSHyQGY= got: sha256-sGa++ywE9kYw9VnPKeYyzaRJsYOzF0mNE7C9c2TdUNQ=

Do I need to regenerate the SHA now that riscv-semihosting was updated?

**Comment by beezow** [comment]
> > > @beezow looks like nix flake check is failing: https://github.com/rivosinc/hubris/actions/runs/3300635406/jobs/5445349052. Do you know how to start debugging?
> > 
> > 
> > error: hash mismatch in fixed-output derivation '/nix/store/b1bp8zff3d1yamw0rc4vsdzvc0mc8izz-riscv-semihosting-ec93c72.drv': specified: sha256-JzQyv2/4F1FBclFZUsIOJ1TREaBIKQp/TOZhBSHyQGY= got: sha256-sGa++ywE9kYw9VnPKeYyzaRJsYOzF0mNE7C9c2TdUNQ=
> 
> Do I need to regenerate the SHA now that riscv-semihosting was updated?

Yea, just replace the hash in `nix/hubris.nix` with the one it suggested.  See https://github.com/rivosinc/hubris/pull/64/commits/64e9f4e50da93ed69e3b7ab7e37be1437b2f1c8c.

Anytime a git dependency changes, the corresponding hash there will also need to be changed.

**Comment by furquan-rivos** [comment]
> > > > @beezow looks like nix flake check is failing: https://github.com/rivosinc/hubris/actions/runs/3300635406/jobs/5445349052. Do you know how to start debugging?
> > > 
> > > 
> > > error: hash mismatch in fixed-output derivation '/nix/store/b1bp8zff3d1yamw0rc4vsdzvc0mc8izz-riscv-semihosting-ec93c72.drv': specified: sha256-JzQyv2/4F1FBclFZUsIOJ1TREaBIKQp/TOZhBSHyQGY= got: sha256-sGa++ywE9kYw9VnPKeYyzaRJsYOzF0mNE7C9c2TdUNQ=
> > 
> > 
> > Do I need to regenerate the SHA now that riscv-semihosting was updated?
> 
> Yea, just replace the hash in `nix/hubris.nix` with the one it suggested. See [64e9f4e](https://github.com/rivosinc/hubris/commit/64e9f4e50da93ed69e3b7ab7e37be1437b2f1c8c).
> 
> Anytime a git dependency changes, the corresponding hash there will also need to be changed.

Is there a way to regenerate this proactively instead of letting nix complain and copy that?

**Comment by beezow** [comment]
> > > > > @beezow looks like nix flake check is failing: https://github.com/rivosinc/hubris/actions/runs/3300635406/jobs/5445349052. Do you know how to start debugging?
> > > > 
> > > > 
> > > > error: hash mismatch in fixed-output derivation '/nix/store/b1bp8zff3d1yamw0rc4vsdzvc0mc8izz-riscv-semihosting-ec93c72.drv': specified: sha256-JzQyv2/4F1FBclFZUsIOJ1TREaBIKQp/TOZhBSHyQGY= got: sha256-sGa++ywE9kYw9VnPKeYyzaRJsYOzF0mNE7C9c2TdUNQ=
> > > 
> > > 
> > > Do I need to regenerate the SHA now that riscv-semihosting was updated?
> > 
> > 
> > Yea, just replace the hash in `nix/hubris.nix` with the one it suggested. See [64e9f4e](https://github.com/rivosinc/hubris/commit/64e9f4e50da93ed69e3b7ab7e37be1437b2f1c8c).
> > Anytime a git dependency changes, the corresponding hash there will also need to be changed.
> 
> Is there a way to regenerate this proactively instead of letting nix complain and copy that?

Not that I know of, @picostove ?

**Comment by beezow** [comment]
There are some alternative ways to vendor cargo dependencies which don't require this, but I haven't figured out how to incorporate them with `xtask`.  https://rivosinc.atlassian.net/browse/SW-819

**Comment by furquan-rivos** [comment]
> > > > @beezow looks like nix flake check is failing: https://github.com/rivosinc/hubris/actions/runs/3300635406/jobs/5445349052. Do you know how to start debugging?
> > > 
> > > 
> > > error: hash mismatch in fixed-output derivation '/nix/store/b1bp8zff3d1yamw0rc4vsdzvc0mc8izz-riscv-semihosting-ec93c72.drv': specified: sha256-JzQyv2/4F1FBclFZUsIOJ1TREaBIKQp/TOZhBSHyQGY= got: sha256-sGa++ywE9kYw9VnPKeYyzaRJsYOzF0mNE7C9c2TdUNQ=
> > 
> > 
> > Do I need to regenerate the SHA now that riscv-semihosting was updated?
> 
> Yea, just replace the hash in `nix/hubris.nix` with the one it suggested. See [64e9f4e](https://github.com/rivosinc/hubris/commit/64e9f4e50da93ed69e3b7ab7e37be1437b2f1c8c).
> 
> Anytime a git dependency changes, the corresponding hash there will also need to be changed.

Done. Let's see if this works fine this time.

**Comment by beezow** [comment]
> > > > > @beezow looks like nix flake check is failing: https://github.com/rivosinc/hubris/actions/runs/3300635406/jobs/5445349052. Do you know how to start debugging?
> > > > 
> > > > 
> > > > error: hash mismatch in fixed-output derivation '/nix/store/b1bp8zff3d1yamw0rc4vsdzvc0mc8izz-riscv-semihosting-ec93c72.drv': specified: sha256-JzQyv2/4F1FBclFZUsIOJ1TREaBIKQp/TOZhBSHyQGY= got: sha256-sGa++ywE9kYw9VnPKeYyzaRJsYOzF0mNE7C9c2TdUNQ=
> > > 
> > > 
> > > Do I need to regenerate the SHA now that riscv-semihosting was updated?
> > 
> > 
> > Yea, just replace the hash in `nix/hubris.nix` with the one it suggested. See [64e9f4e](https://github.com/rivosinc/hubris/commit/64e9f4e50da93ed69e3b7ab7e37be1437b2f1c8c).
> > Anytime a git dependency changes, the corresponding hash there will also need to be changed.
> 
> Done. Let's see if this works fine this time.

You can also test it locally by running a `nix flake check`, or if you just want to check the hashes, `nix build .#demo-hifive-inventor` (or any other app).

**Comment by furquan-rivos** [comment]
> > > > > > @beezow looks like nix flake check is failing: https://github.com/rivosinc/hubris/actions/runs/3300635406/jobs/5445349052. Do you know how to start debugging?
> > > > > 
> > > > > 
> > > > > error: hash mismatch in fixed-output derivation '/nix/store/b1bp8zff3d1yamw0rc4vsdzvc0mc8izz-riscv-semihosting-ec93c72.drv': specified: sha256-JzQyv2/4F1FBclFZUsIOJ1TREaBIKQp/TOZhBSHyQGY= got: sha256-sGa++ywE9kYw9VnPKeYyzaRJsYOzF0mNE7C9c2TdUNQ=
> > > > 
> > > > 
> > > > Do I need to regenerate the SHA now that riscv-semihosting was updated?
> > > 
> > > 
> > > Yea, just replace the hash in `nix/hubris.nix` with the one it suggested. See [64e9f4e](https://github.com/rivosinc/hubris/commit/64e9f4e50da93ed69e3b7ab7e37be1437b2f1c8c).
> > > Anytime a git dependency changes, the corresponding hash there will also need to be changed.
> > 
> > 
> > Done. Let's see if this works fine this time.
> 
> You can also test it locally by running a `nix flake check`, or if you just want to check the hashes, `nix build .#demo-hifive-inventor` (or any other app).

Yeah, I checked locally using `nix flake check`, but I was not sure if something else would fail in the CI, which looks like some formatting check failed this time.

**Review by beezow — APPROVED** [review]

**Pull request merged**
