### PR TITLE
RV64 main merge Oct 4

### PR DESCRIPTION
**Pull request by furquan-rivos**
Verified that rv64 qemu tests still pass and rv32 builds fine.

### CODE REVIEW

**Comment by FawazTirmizi** [comment]
Can you give us a diff showing the changes you had to make in the merge commit? I can't seem to get them on here.

**Comment by furquan-rivos** [comment]
> Can you give us a diff showing the changes you had to make in the merge commit? I can't seem to get them on here.

Yes, I will do that. There are more changes that I need to pull in, so working on that right now. Marked the PR as draft until that is done.

**Comment by furquan-rivos** [comment]
These are the merge conflict resolutions generated using `git show 2b76b01ad243885744eb96a6323183e3037eb1ba`:
```
commit 2b76b01ad243885744eb96a6323183e3037eb1ba
Merge: d6d64e30 0a3aa6fc
Author: Furquan Shaikh <furquan@rivosinc.com>
Date:   Tue Oct 4 10:34:23 2022 -0700

    Merge remote-tracking branch 'origin/rivos/main' into dev/furquan/rv64-merge-oct4

diff --cc Cargo.lock
index 21d253fb,692bfb13..d4935c6f
--- a/Cargo.lock
+++ b/Cargo.lock
@@@ -547,18 -614,6 +615,18 @@@ dependencies = 
   "riscv-rt",
  ]
  
 +[[package]]
 +name = "demo-rv64-qemu-virt"
 +version = "0.1.0"
 +dependencies = [
 + "build-util",
 + "cfg-if 0.1.10",
 + "kern",
 + "panic-halt",
-  "riscv 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)",
++ "riscv 0.8.1",
 + "riscv-rt",
 +]
 +
  [[package]]
  name = "demo-stm32f4-discovery"
  version = "0.1.0"
@@@ -3721,14 -4167,20 +4180,28 @@@ dependencies = 
  name = "tests-psc"
  version = "0.1.0"
  
+ [[package]]
+ name = "tests-rot-carrier"
+ version = "0.1.0"
+ dependencies = [
+  "cfg-if 1.0.0",
+  "cortex-m",
+  "cortex-m-rt",
+  "kern",
+  "lpc55-pac",
+  "panic-halt",
+  "panic-itm",
+  "panic-semihosting",
+ ]
+ 
 +[[package]]
 +name = "tests-rv64-qemu-virt"
 +version = "0.1.0"
 +dependencies = [
 + "build-util",
 + "kern",
 +]
 +
  [[package]]
  name = "tests-stm32f4"
  version = "0.1.0"
diff --cc app/demo-rv64-qemu-virt/Cargo.toml
index 2888efd0,00000000..4242aead
mode 100644,000000..100644
--- a/app/demo-rv64-qemu-virt/Cargo.toml
+++ b/app/demo-rv64-qemu-virt/Cargo.toml
@@@ -1,24 -1,0 +1,24 @@@
 +[package]
 +name = "demo-rv64-qemu-virt"
 +version = "0.1.0"
 +edition = "2021"
 +
 +[dependencies]
 +cfg-if = "0.1.10"
 +panic-halt = "0.2.0"
- riscv = "0.8.0"
++riscv = { git = "https://github.com/rivosinc/riscv", branch = "rivos/dev" }
 +riscv-rt = "0.9.0"
 +
 +[dependencies.kern]
 +path = "../../sys/kern"
 +default-features = false
 +features = ["vectored-interrupts", "klog-semihosting"]
 +
 +[build-dependencies]
 +build-util = {path = "../../build/util"}
 +
 +# this lets you use `cargo fix`!
 +[[bin]]
 +name = "demo-rv64-qemu-virt"
 +test = false
 +bench = false
diff --cc app/demo-stm32g0-nucleo/Cargo.toml
index 3ee8ed08,c4263638..cb3dffb7
--- a/app/demo-stm32g0-nucleo/Cargo.toml
+++ b/app/demo-stm32g0-nucleo/Cargo.toml
@@@ -5,9 -5,9 +5,10 @@@ name = "demo-stm32g0-nucleo
  version = "0.1.0"
  
  [features]
 -itm = ["panic-itm"]
 -semihosting = ["panic-semihosting"]
 +itm = ["panic-itm", "kern/klog-itm"]
 +semihosting = ["panic-semihosting", "klog-semihosting"]
 +klog-semihosting = ["kern/klog-semihosting"]
+ g030 = ["stm32g0/stm32g030"]
  g031 = ["stm32g0/stm32g031"]
  g070 = ["stm32g0/stm32g070"]
  g0b1 = ["stm32g0/stm32g0b1"]
diff --cc build/xtask/src/config.rs
index e766287d,1db3470e..cf7cfd14
--- a/build/xtask/src/config.rs
+++ b/build/xtask/src/config.rs
@@@ -7,11 -7,11 +7,13 @@@ use std::hash::Hasher
  use std::ops::Range;
  use std::path::{Path, PathBuf};
  
 +use abi::AbiSize;
 +
- use anyhow::{anyhow, bail, Result};
+ use anyhow::{anyhow, bail, Context, Result};
  use indexmap::IndexMap;
- use serde::Deserialize;
+ use serde::{Deserialize, Serialize};
+ 
+ use crate::auxflash::{build_auxflash, AuxFlash, AuxFlashData};
  
  /// A `RawConfig` represents an `app.toml` file that has been deserialized,
  /// but may not be ready for use.  In particular, we use the `chip` field
@@@ -324,13 -379,30 +381,30 @@@ impl Config 
              .collect()
      }
  
+     pub fn all_regions(
+         &self,
+         region: String,
 -    ) -> Result<IndexMap<String, Range<u32>>> {
++    ) -> Result<IndexMap<String, Range<AbiSize>>> {
+         let outputs: &Vec<Output> = self
+             .outputs
+             .get(&region)
+             .ok_or_else(|| anyhow!("couldn't find region {}", region))?;
 -        let mut memories: IndexMap<String, Range<u32>> = IndexMap::new();
++        let mut memories: IndexMap<String, Range<AbiSize>> = IndexMap::new();
+ 
+         for o in outputs {
+             memories.insert(o.name.clone(), o.address..o.address + o.size);
+         }
+ 
+         Ok(memories)
+     }
+ 
      pub fn image_memories(
          &self,
          region: String,
 -    ) -> Result<IndexMap<String, Range<u32>>> {
 -        let mut memories: IndexMap<String, Range<u32>> = IndexMap::new();
 +    ) -> Result<IndexMap<String, Range<AbiSize>>> {
 +        let mut memories: IndexMap<String, Range<AbiSize>> = IndexMap::new();
          for a in &self.external_images {
-             if let Some(r) = self.memories(&a)?.get(&region) {
+             if let Some(r) = self.memories(a)?.get(&region) {
                  memories.insert(a.clone(), r.start..r.end);
              }
          }
@@@ -506,13 -587,15 +593,15 @@@ pub struct Task 
      pub task_slots: IndexMap<String, String>,
      #[serde(default)]
      pub config: Option<ordered_toml::Value>,
+     #[serde(default)]
+     pub uses_secure_entry: bool,
  }
  
- #[derive(Clone, Debug, Deserialize)]
+ #[derive(Clone, Debug, Serialize, Deserialize)]
  #[serde(rename_all = "kebab-case", deny_unknown_fields)]
  pub struct Peripheral {
 -    pub address: u32,
 -    pub size: u32,
 +    pub address: AbiSize,
 +    pub size: AbiSize,
      #[serde(default)]
      pub interrupts: BTreeMap<String, u32>,
  }
diff --cc build/xtask/src/dist.rs
index a751af58,11b18023..ba6184f4
--- a/build/xtask/src/dist.rs
+++ b/build/xtask/src/dist.rs
@@@ -10,8 -10,8 +10,9 @@@ use std::ops::Range
  use std::path::{Path, PathBuf};
  use std::process::Command;
  
 +use abi::AbiSize;
  use anyhow::{anyhow, bail, Context, Result};
+ use atty::Stream;
  use colored::*;
  use indexmap::IndexMap;
  use path_slash::PathBufExt;
@@@ -276,6 -262,15 +278,15 @@@ pub fn list_tasks(app_toml: &Path) -> R
      Ok(())
  }
  
+ #[derive(Debug)]
+ pub struct SecureData {
 -    secure: Range<u32>,
 -    nsc: Range<u32>,
++    secure: Range<AbiSize>,
++    nsc: Range<AbiSize>,
+ }
+ 
+ /// Represents allocations and free spaces for a particular image
 -type AllocationMap = (Allocations, IndexMap<String, Range<u32>>);
++type AllocationMap = (Allocations, IndexMap<String, Range<AbiSize>>);
+ 
  pub fn package(
      verbose: bool,
      edges: bool,
@@@ -483,6 -493,112 +509,112 @@@
      Ok(allocated)
  }
  
+ fn secure_update(
+     cfg: &PackageConfig,
+     allocs: &Allocations,
 -    all_output_sections: &mut BTreeMap<u32, LoadSegment>,
++    all_output_sections: &mut BTreeMap<AbiSize, LoadSegment>,
+     image_name: &str,
+ ) -> Result<Option<SecureData>> {
+     if let Some(secure) = &cfg.toml.secure_task {
+         if !cfg.toml.tasks.contains_key(secure) {
+             bail!("secure task named {} not found!", secure);
+         }
+         // The secure task is our designated TrustZone region. We expect
+         // this to have a non-secure callable (NSC) region for entry
+         // pointers and a .tz_table of entry points
+         let secure_bin = std::fs::read(&cfg.img_file(&secure, image_name))?;
+         let secure_elf = goblin::elf::Elf::parse(&secure_bin)?;
+ 
+         let nsc = match elf::get_section_by_name(&secure_elf, ".nsc") {
+             Some(s) => s,
+             _ => bail!("Couldn't find the nsc region in the secure task"),
+         };
+ 
+         if nsc.sh_size == 0 {
+             bail!("nsc region is zero?");
+         }
+ 
+         let tz_table = match elf::get_section_by_name(&secure_elf, ".tz_table")
+         {
+             Some(s) => s,
+             _ => bail!("Couldn't find the TZ table in the secure task"),
+         };
+ 
+         if tz_table.sh_size == 0 {
+             bail!("tz_table is zero. This does not seem correct.");
+         }
+ 
+         let flash = &allocs.tasks[secure]["flash"];
+ 
+         for (name, t) in &cfg.toml.tasks {
+             // Any task listed as using secure needs to have an appropriately
+             // sized .tz_table section which will get updated
+             if t.uses_secure_entry {
+                 if t.name == *secure {
+                     bail!("Secure task is selecting the secure region! This is wrong!");
+                 }
+ 
+                 let mut bin = std::fs::read(&cfg.img_file(name, image_name))?;
+                 let elf = goblin::elf::Elf::parse(&bin)?;
+ 
+                 let s = match elf::get_section_by_name(&elf, ".tz_table") {
+                     Some(s) => s,
+                     _ => bail!("task {} wants to use the secure region but doesn't have a slot for the TZ table", name),
+                 };
+ 
+                 if s.sh_size != tz_table.sh_size {
+                     bail!("task {} has table size {:x} but secure table size is {:x}",
+                             name, s.sh_size, tz_table.sh_size);
+                 }
+ 
+                 let target_start = s.sh_offset as usize;
+                 let target_end = (s.sh_offset + s.sh_size) as usize;
+ 
+                 let table_start = tz_table.sh_offset as usize;
+                 let table_end =
+                     (tz_table.sh_offset + tz_table.sh_size) as usize;
+ 
+                 bin[target_start..target_end]
+                     .clone_from_slice(&secure_bin[table_start..table_end]);
+ 
+                 std::fs::write(
+                     &cfg.img_file(format!("{}.modified", name), image_name),
+                     &bin,
+                 )?;
+                 std::fs::copy(
+                     &cfg.img_file(format!("{}.modified", name), image_name),
+                     &cfg.img_file(name, image_name),
+                 )?;
+ 
+                 let mut symbol_table = BTreeMap::default();
+                 let _ = load_elf(
+                     &cfg.img_file(name, image_name),
+                     all_output_sections,
+                     &mut symbol_table,
+                 )?;
+             }
+         }
+ 
 -        let start = nsc.sh_addr as u32;
 -        let end = (nsc.sh_addr + nsc.sh_size) as u32;
++        let start = nsc.sh_addr as AbiSize;
++        let end = (nsc.sh_addr + nsc.sh_size) as AbiSize;
+ 
+         Ok(Some(SecureData {
+             secure: flash.start..flash.end,
+             nsc: start..end,
+         }))
+     } else {
+         if cfg
+             .toml
+             .tasks
+             .iter()
+             .any(|(_, task)| task.uses_secure_entry)
+         {
+             bail!("task is using secure entry but no secure task is found!");
+         }
+         Ok(None)
+     }
+ }
+ 
  /// Convert SREC to other formats for convenience.
  fn translate_srec_to_other_formats(
      cfg: &PackageConfig,
@@@ -821,11 -976,12 +992,12 @@@ fn task_entry_point
  fn build_kernel(
      cfg: &PackageConfig,
      allocs: &Allocations,
 -    all_output_sections: &mut BTreeMap<u32, LoadSegment>,
 -    all_memories: &IndexMap<String, Range<u32>>,
 -    entry_points: &HashMap<String, u32>,
 +    all_output_sections: &mut BTreeMap<AbiSize, LoadSegment>,
 +    all_memories: &IndexMap<String, Range<AbiSize>>,
 +    entry_points: &HashMap<String, AbiSize>,
      image_name: &str,
+     secure: &Option<SecureData>,
 -) -> Result<(u32, BTreeMap<String, u32>)> {
 +) -> Result<(AbiSize, BTreeMap<String, AbiSize>)> {
      let mut image_id = fnv::FnvHasher::default();
      all_output_sections.hash(&mut image_id);
  
@@@ -895,11 -1057,12 +1073,10 @@@
  fn update_image_header(
      input: &Path,
      output: &Path,
 -    map: &IndexMap<String, Range<u32>>,
 -    all_output_sections: &mut BTreeMap<u32, LoadSegment>,
 +    map: &IndexMap<String, Range<AbiSize>>,
 +    all_output_sections: &mut BTreeMap<AbiSize, LoadSegment>,
+     secure: &Option<SecureData>,
  ) -> Result<bool> {
-     use zerocopy::AsBytes;
 -    use goblin::container::Container;
--
      let mut file_image = std::fs::read(input)?;
      let elf = goblin::elf::Elf::parse(&file_image)?;
  
@@@ -924,12 -1090,11 +1101,11 @@@
                  let mut end = 0;
  
                  for (addr, sec) in all_output_sections {
 -                    if (*addr as u32) > flash.start
 -                        && (*addr as u32) < flash.end
 -                        && (*addr as u32) > end
 +                    if (*addr as AbiSize) > flash.start
 +                        && (*addr as AbiSize) < flash.end
++                        && (*addr as AbiSize) > end
                      {
-                         if (*addr as AbiSize) > end {
-                             end = addr + (sec.data.len() as AbiSize);
-                         }
 -                        end = addr + (sec.data.len() as u32);
++                        end = addr + (sec.data.len() as AbiSize);
                      }
                  }
  
@@@ -1027,9 -1259,11 +1278,11 @@@ fn generate_linker_aliases
  fn generate_task_linker_script(
      arch_target: ArchTarget,
      name: &str,
 -    map: &BTreeMap<String, Range<u32>>,
 +    map: &BTreeMap<String, Range<AbiSize>>,
      sections: Option<&IndexMap<String, String>>,
 -    stacksize: u32,
 -    images: &IndexMap<String, Range<u32>>,
 +    stacksize: AbiSize,
++    images: &IndexMap<String, Range<AbiSize>>,
+     image_name: &str,
  ) -> Result<()> {
      // Put the linker script somewhere the linker can find it
      let mut linkscr = File::create(Path::new(&format!("target/{}", name)))?;
@@@ -1196,20 -1449,26 +1473,26 @@@ fn build
          .map(|r| format!(" --remap-path-prefix={}={}", r.0.display(), r.1))
          .collect();
  
-     cmd.env(
-         "RUSTFLAGS",
-         &format!(
-             "
-              -C link-arg=-z -C link-arg=common-page-size=0x20 \
-              -C link-arg=-z -C link-arg=max-page-size=0x20 \
-              -C llvm-args=--enable-machine-outliner=never \
-              -C overflow-checks=y \
-              -C metadata={} \
-              {}
-              ",
-             cfg.link_script_hash, remap_path_prefix,
-         ),
+     let mut rustflags: String = format!(
+         "
+          -C link-arg=-z -C link-arg=common-page-size=0x20 \
+          -C link-arg=-z -C link-arg=max-page-size=0x20 \
+          -C llvm-args=--enable-machine-outliner=never \
+          -C overflow-checks=y \
+          -C metadata={} \
+          {}
+          ",
+         cfg.link_script_hash, remap_path_prefix,
      );
+ 
+     match cfg.arch_target {
 -        ArchTarget::RISCV => {
++        ArchTarget::RISCV32 => {
+             rustflags.push_str(" -C link-arg=--orphan-handling=error")
+         }
 -        ArchTarget::ARM => {}
++        _ => {}
+     }
+ 
+     cmd.env("RUSTFLAGS", &rustflags);
      cmd.arg("--");
      cmd.arg("-C")
          .arg("link-arg=-Tlink.x")
@@@ -1390,13 -1670,11 +1695,13 @@@ pub fn allocate_all
  
      for image_name in &toml.image_names {
          let mut allocs = Allocations::default();
-         let mut free = toml.memories(&image_name)?;
+         let mut free = toml.memories(image_name)?;
          let kernel_requests = &kernel.requires;
  
 -        let mut task_requests: BTreeMap<&str, BTreeMap<u32, VecDeque<&str>>> =
 -            BTreeMap::new();
 +        let mut task_requests: BTreeMap<
 +            &str,
 +            BTreeMap<AbiSize, VecDeque<&str>>,
 +        > = BTreeMap::new();
  
          for name in tasks.keys() {
              for (mem, amt) in task_sizes[name.as_str()].iter() {
@@@ -1575,9 -1853,10 +1880,10 @@@ pub struct KernelConfig 
  /// - Some number of `Interrupt` records routing interrupts to tasks.
  pub fn make_kconfig(
      toml: &Config,
 -    task_allocations: &BTreeMap<String, BTreeMap<String, Range<u32>>>,
 -    entry_points: &HashMap<String, u32>,
 +    task_allocations: &BTreeMap<String, BTreeMap<String, Range<AbiSize>>>,
 +    entry_points: &HashMap<String, AbiSize>,
      image_name: &str,
+     secure: &Option<SecureData>,
  ) -> Result<KernelConfig> {
      // Generate the three record sections concurrently.
      let mut regions = vec![];
@@@ -1923,29 -2220,33 +2243,33 @@@ fn load_elf
  
          flash += size;
  
-         // Check for address overlap
-         let range = addr..addr + size as AbiSize;
-         if let Some(overlap) = output.range(range.clone()).next() {
-             if overlap.1.source_file != input {
-                 bail!(
-                     "{}: address range {:x?} overlaps {:x} \
+         // We use this function to re-load an ELF file after we've modfified
+         // it. Don't check for overlap if this happens.
+         if !output.contains_key(&addr) {
 -            let range = addr..addr + size as u32;
++            let range = addr..addr + size as AbiSize;
+             if let Some(overlap) = output.range(range.clone()).next() {
+                 if overlap.1.source_file != input {
+                     bail!(
+                         "{}: address range {:x?} overlaps {:x} \
                      (from {}); does {} have an insufficient amount of flash?",
-                     input.display(),
-                     range,
-                     overlap.0,
-                     overlap.1.source_file.display(),
-                     input.display(),
-                 );
-             } else {
-                 bail!(
-                     "{}: ELF file internally inconsistent: \
+                         input.display(),
+                         range,
+                         overlap.0,
+                         overlap.1.source_file.display(),
+                         input.display(),
+                     );
+                 } else {
+                     bail!(
+                         "{}: ELF file internally inconsistent: \
                      address range {:x?} overlaps {:x}",
-                     input.display(),
-                     range,
-                     overlap.0,
-                 );
+                         input.display(),
+                         range,
+                         overlap.0,
+                     );
+                 }
              }
          }
+ 
          output.insert(
              addr,
              LoadSegment {
diff --cc sys/abi/src/lib.rs
index f3acea23,5bac5c89..1beda82b
--- a/sys/abi/src/lib.rs
+++ b/sys/abi/src/lib.rs
@@@ -648,9 -634,11 +648,11 @@@ pub const HEADER_MAGIC: AbiSize = 0x153
  #[repr(C)]
  #[derive(Default, AsBytes, FromBytes)]
  pub struct ImageHeader {
 -    pub magic: u32,
 -    pub total_image_len: u32,
 +    pub magic: AbiSize,
 +    pub total_image_len: AbiSize,
      pub sau_entries: [SAUEntry; 8],
+     pub version: u32,
+     pub epoch: u32,
  }
  
  // Corresponds to the ARM vector table, limited to what we need
diff --cc task/jefe/Cargo.toml
index 5baf69d1,563d606b..9a3d377f
--- a/task/jefe/Cargo.toml
+++ b/task/jefe/Cargo.toml
@@@ -35,8 -35,8 +35,8 @@@ cortex-m = { version = "0.7", features 
  cortex-m-semihosting = { version = "0.5.0", optional = true }
  armv6m-atomic-hack = {path = "../../lib/armv6m-atomic-hack"}
  
 -[target.'cfg(target_arch = "riscv32")'.dependencies]
 +[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
- riscv = { version = "0.8" }
+ riscv = { git = "https://github.com/rivosinc/riscv", branch = "rivos/dev" }
  riscv-semihosting = { git = "https://github.com/rivosinc/riscv-semihosting", branch = "dev/fawaz/privilege-features", optional = true, features = ["default", "user-mode"] }
  riscv-pseudo-atomics = { git = "https://github.com/rivosinc/riscv-psuedo-atomics", branch = "rivos/main", features = ["default", "user-mode"] }
  
diff --cc test/test-assist/Cargo.toml
index a4a6c488,ee2ec9c0..3aefb410
--- a/test/test-assist/Cargo.toml
+++ b/test/test-assist/Cargo.toml
@@@ -17,8 -17,8 +17,8 @@@ build-util = {path = "../../build/util"
  cortex-m = {version = "0.7", features = ["inline-asm"]}
  cortex-m-semihosting = { version = "0.5.0", optional = true }
  
 -[target.'cfg(target_arch = "riscv32")'.dependencies]
 +[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
- riscv = { version = "0.8" }
+ riscv = { git = "https://github.com/rivosinc/riscv", branch = "rivos/dev" }
  riscv-semihosting = { git = "https://github.com/rivosinc/riscv-semihosting", branch = "dev/fawaz/privilege-features", features = ["default", "user-mode"] }
  
  [features]
diff --cc test/test-runner/Cargo.toml
index 94308f6c,95eb0f73..14ee7358
--- a/test/test-runner/Cargo.toml
+++ b/test/test-runner/Cargo.toml
@@@ -19,8 -19,8 +19,8 @@@ cortex-m = {version = "0.7", features 
  armv6m-atomic-hack = {path = "../../lib/armv6m-atomic-hack"}
  cortex-m-semihosting = { version = "0.5.0", optional = true }
  
 -[target.'cfg(target_arch = "riscv32")'.dependencies]
 +[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
- riscv = { version = "0.8" }
+ riscv = { git = "https://github.com/rivosinc/riscv", branch = "rivos/dev" }
  riscv-semihosting = { git = "https://github.com/rivosinc/riscv-semihosting", branch = "dev/fawaz/privilege-features", features = ["default", "user-mode"] }
  riscv-pseudo-atomics = { git = "https://github.com/rivosinc/riscv-psuedo-atomics", branch = "rivos/main", features = ["default", "user-mode"] }
  
```

**Review by FawazTirmizi — APPROVED** [review]
Looked through the diff, everything seems fine to me.

**Pull request merged**
